language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
notifications:
  slack:
    secure: aAZYAn3tV6SAQ2OY/jpuzmEH8TKrxubUscYIXpQnEuyym7L4gPuZPY9BptOFTzScKp+kn4SlpjWeozhe49BbCBU8TNVqLrlY6+ync9pJkdioTaUZ8j4KRJpJtU9GBh7HUt+KUDL3clqefQxPwKMx0ORRQfOsxxpdjHyMa1VTigZInZRRwiB0H87F3TXOZVK9HRBpooErkE3ScRXLrQnT4qrVV1yCbeG8Ly6jmlsNedt4WlCXJftLI/YNQ5+j2Z7OksJCdQFGzRQwe9g9jx8FuFyGBKJUPCAT+YdIQarayb50HBj1fRwaP2Wmb1OeucZbxVWmt3iaNdci06BQMFBMIIw3oSwE2moAgZOpZbtPfMfdww6eQtHal31wAiT26YDpGSugsjkwz7DCKxvvqQra43viVM1UJjBebwv+mK6NpNG+prEzyqyEp11sFAaDn+RmalSR7FzGWIte7i7aGSIdL3jzG/cpOaiXwadoYzsFABpccosmuJ7netzTVMfijgMiUT2RkaKcd98aZ26i5UnwYQQ2rRTFBF6mG2vWgpF98QvAdA0y6NdH9ssV80M8pva2vet4KdrB7WqiYFFgJqoFjZyNWdDHF5WIVKzgY7Js/uN4FKdT0fgXwxxkHlDaJMTKT1I+1WJL59/d8SI8i8Uw7uH5DGQ3nzSEYagLWS5a3Cs=
