language: scala
scala:
# When updating Scala versions, also check the excludes
# in build matrix below.
- 2.11.12
- 2.12.6
jdk:
- oraclejdk8
- oraclejdk9
- oraclejdk10
- oraclejdk11
env:
  matrix:
    - SCRIPT=scripts/test-sbt
    - SCRIPT=scripts/test-gradle
script:
- $SCRIPT
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.gradle/caches"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm

# Exclude some combinations from build matrix. See:
# https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix
matrix:
  exclude:
    - scala: 2.11.12
      jdk: oraclejdk9
    - scala: 2.11.12
      jdk: oraclejdk10
    - scala: 2.11.12
      jdk: oraclejdk11
  allow_failures:
    # We should allow failures here since Java 11 removed some modules including
    # java.xml.bind which we are adding when running with Java 9+. For more details
    # see http://openjdk.java.net/jeps/320
    #
    # Play already has a fix for that, but it needs to be backported and released
    # for 2.6.x: https://github.com/playframework/playframework/pull/8382
    - jdk: oraclejdk11

# See https://blog.travis-ci.com/2014-03-13-slack-notifications/
# created with travis encrypt command line tool
notifications:
  slack:
    secure: aAZYAn3tV6SAQ2OY/jpuzmEH8TKrxubUscYIXpQnEuyym7L4gPuZPY9BptOFTzScKp+kn4SlpjWeozhe49BbCBU8TNVqLrlY6+ync9pJkdioTaUZ8j4KRJpJtU9GBh7HUt+KUDL3clqefQxPwKMx0ORRQfOsxxpdjHyMa1VTigZInZRRwiB0H87F3TXOZVK9HRBpooErkE3ScRXLrQnT4qrVV1yCbeG8Ly6jmlsNedt4WlCXJftLI/YNQ5+j2Z7OksJCdQFGzRQwe9g9jx8FuFyGBKJUPCAT+YdIQarayb50HBj1fRwaP2Wmb1OeucZbxVWmt3iaNdci06BQMFBMIIw3oSwE2moAgZOpZbtPfMfdww6eQtHal31wAiT26YDpGSugsjkwz7DCKxvvqQra43viVM1UJjBebwv+mK6NpNG+prEzyqyEp11sFAaDn+RmalSR7FzGWIte7i7aGSIdL3jzG/cpOaiXwadoYzsFABpccosmuJ7netzTVMfijgMiUT2RkaKcd98aZ26i5UnwYQQ2rRTFBF6mG2vWgpF98QvAdA0y6NdH9ssV80M8pva2vet4KdrB7WqiYFFgJqoFjZyNWdDHF5WIVKzgY7Js/uN4FKdT0fgXwxxkHlDaJMTKT1I+1WJL59/d8SI8i8Uw7uH5DGQ3nzSEYagLWS5a3Cs=
